# Generated by Django 5.2.15 on 2026-06-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Helpline Hello Naogaon', max_length=200)),
                ('hero_title', models.CharField(default='Welcome to Helpline Hello Naogaon', max_length=200)),
                ('hero_subtitle', models.TextField(default='We are dedicated to helping our community.')),
                ('about_text', models.TextField(blank=True, default='')),
                ('mission_text', models.TextField(blank=True, default='')),
                ('vision_text', models.TextField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_address', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
