# Generated by Django 5.2.15 on 2026-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Set True for the large main image in the About grid')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Image',
                'verbose_name_plural': 'About Images',
                'ordering': ['-is_featured', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StatCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('icon_class', models.CharField(help_text="e.g. 'fas fa-tint', 'fas fa-users'", max_length=50)),
                ('badge_color', models.CharField(default='danger', help_text='bootstrap badge color: danger, success, warning, primary, info', max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stat Counter',
                'verbose_name_plural': 'Stat Counters',
                'ordering': ['order'],
            },
        ),
    ]
