# Generated by Django 5.2.15 on 2026-08-08 14:10

from django.db import migrations, models


def convert_to_utf8mb4(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        schema_editor.execute(
            "ALTER TABLE core_sitesetting CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutimage_statcounter'),
    ]

    operations = [
        migrations.RunPython(convert_to_utf8mb4, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='sitesetting',
            name='about_heading',
            field=models.CharField(default='আমাদের সম্পর্কে', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_banner_button_text',
            field=models.CharField(default='স্বেচ্ছাসেবক হন', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_banner_title',
            field=models.CharField(default='আসুন, আমরা সবাই মিলে একটি মানবিক ও সুন্দর সমাজ গড়ে তুলি', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/hello.naogaon'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_about',
            field=models.TextField(blank=True, default='Helpline Hello Naogaon একটি স্বেচ্ছাসেবী সংগঠন। আমাদের লক্ষ্য সমাজকে এগিয়ে নিয়ে যাওয়া এবং অসহায় মানুষের পাশে দাঁড়ানো।'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_map_embed_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_badge',
            field=models.CharField(default='মানবতার পাশে, নওগাঁর প্রতিটি মানুষের জন্য', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(default='সবসময় আপনার পাশে - একটি স্বেচ্ছাসেবী সংগঠন', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='+880 1730-XXXXXX', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_text',
            field=models.TextField(blank=True, default='Helpline Hello Naogaon একটি স্বেচ্ছাসেবী ও মানবিক সংগঠন। আমরা রক্তদান, শিক্ষা সহায়তা, মানবিক সহায়তা, পরিবেশ সুরক্ষা ও দুর্যোগকালীন সেবাসহ বিভিন্ন সামাজিক কার্যক্রম পরিচালনা করে থাকি।'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_address',
            field=models.TextField(blank=True, default='Helpline Hello Naogaon Public Library, মহাদেবপুর, নওগাঁ - ৬৬০০'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, default='hello.naogaon@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, default='+880 1730-XXXXXX', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(default='আমরা একটি অরাজনৈতিক, অলাভজনক ও স্বেচ্ছাসেবী সংগঠন, যা সমাজের অসহায় মানুষের পাশে দাঁড়াতে প্রতিশ্রুতিবদ্ধ।'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Helpline Hello Naogaon', max_length=200),
        ),
    ]
