# Generated by Django 5.2.15 on 2026-08-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
