# Generated by Django 5.2.15 on 2026-08-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='google_map_embed_url',
            field=models.TextField(blank=True, default='', help_text='Google Map Embed Code (<iframe...>) বা ম্যাপের লিঙ্ক দিন।'),
        ),
    ]
