# Generated by Django 4.2.30 on 2026-09-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ক্যাটাগরির নাম')),
                ('icon', models.CharField(default='fas fa-phone-alt', max_length=50, verbose_name='আইকন ক্লাস (FontAwesome)')),
                ('badge_color', models.CharField(default='danger', help_text='Bootstrap কালার যেমন: danger, primary, success, warning, info', max_length=30, verbose_name='কালার থিম (danger, primary, success, warning, info)')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রমিক নম্বর')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'জরুরি সেবার ক্যাটাগরি',
                'verbose_name_plural': 'জরুরি সেবার ক্যাটাগরিসমূহ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='সেবা / প্রতিষ্ঠানের নাম')),
                ('phone_numbers', models.CharField(help_text='একাধিক নম্বর থাকলে স্ল্যাশ (/) দিয়ে লিখুন, যেমন: ০২৫৮৮৮৮২৫২৩ / ০১৭১৫-২৯২৩৭৭', max_length=255, verbose_name='ফোন নম্বরসমূহ')),
                ('subtext', models.CharField(blank=True, help_text='যেমন: পুলিশ, ফায়ার সার্ভিস ও অ্যাম্বুলেন্স সেবা', max_length=255, verbose_name='ছোট বিবরণ / ট্যাগলাইন')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='ঠিকানা / লোকেশন')),
                ('badge_text', models.CharField(blank=True, help_text='যেমন: ২৪ ঘণ্টা জরুরি, টোল ফ্রি, হটলাইন: ১৬৯৯৯', max_length=60, verbose_name='ব্যাজ টেক্সট')),
                ('icon_class', models.CharField(default='fas fa-phone-alt', max_length=50, verbose_name='আইকন ক্লাস')),
                ('is_hotline', models.BooleanField(default=False, verbose_name='হটলাইন / বিশেষ হাইলাইট')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রমিক নম্বর')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.emergencycategory', verbose_name='ক্যাটাগরি')),
            ],
            options={
                'verbose_name': 'জরুরি সেবা নম্বর',
                'verbose_name_plural': 'জরুরি সেবা নম্বরসমূহ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
