# Generated by Django 4.2.30 on 2026-10-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emergencycategory_emergencyservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='trade_license_number',
            field=models.CharField(blank=True, default='TRAD/MDHP/002341/2024', help_text='ট্রেড লাইসেন্স বা সরকারি নিবন্ধন নম্বর', max_length=100),
        ),
    ]
