# Generated by Django 4.2.30 on 2026-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesetting_trade_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='admin_phone',
            field=models.CharField(blank=True, default='01916314315', help_text='প্রধান অফিশিয়াল অ্যাডমিন নম্বর (সকল অ্যালার্ট SMS, ফিরতি মেসেজ ও ওয়েবসাইটে সিঙ্ক থাকবে)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, default='01916314315', max_length=50),
        ),
    ]
