# Generated by Django 4.2.30 on 2026-10-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesetting_admin_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='payment_banner',
            field=models.ImageField(blank=True, help_text='পেমেন্ট গেটওয়ে পার্টনার ব্যানার (PayStation / bKash / Nagad / Cards Banner)', null=True, upload_to='site/'),
        ),
    ]
