# Generated by Django 5.2.15 on 2026-08-21 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_blooddonor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-application_date'], 'verbose_name': 'Volunteer Member', 'verbose_name_plural': 'Volunteer Members'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True, verbose_name='রক্তের গ্রুপ'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/', verbose_name='ছবি'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_public_details',
            field=models.BooleanField(default=True, verbose_name='মোবাইল নম্বর ও বিস্তারিত তথ্য সকলের জন্য প্রদর্শন করতে চান?'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='সদস্য আইডি'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='পেশা'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='নিবন্ধনের তারিখ'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='পূর্ণ নাম'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='মোবাইল নম্বর'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
