# Generated by Django 5.2.15 on 2026-08-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_alter_volunteer_options_volunteer_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='is_public_details',
            field=models.BooleanField(default=True, verbose_name='তথ্য সকলের জন্য প্রদর্শন করতে চান?'),
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='সদস্য আইডি (যদি থাকে)'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_donated',
            field=models.DateField(blank=True, null=True, verbose_name='সর্বশেষ রক্তদানের তারিখ'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='রক্তের গ্রুপ'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='তালিকাভুক্তির তারিখ'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='পূর্ণ নাম'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='রক্তদানে সক্রিয়'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='last_donated',
            field=models.DateField(blank=True, null=True, verbose_name='সর্বশেষ রক্তদানের তারিখ'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='location',
            field=models.CharField(help_text='Area / Thana in Naogaon', max_length=200, verbose_name='এলাকা / ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='মোবাইল নম্বর'),
        ),
    ]
