# Generated by Django 5.2.15 on 2026-08-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_blooddonor_is_public_details_blooddonor_member_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='প্রতিশ্রুত আর্থিক পরিমাণ (টাকা)'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contribution_frequency',
            field=models.CharField(blank=True, choices=[('none', 'কোনো নির্দিষ্ট প্রতিশ্রুতি নেই / ইচ্ছানুযায়ী'), ('monthly', 'মাসিক (প্রতি মাসে)'), ('weekly', 'সাপ্তাহিক (প্রতি সপ্তাহে)'), ('yearly', 'বাৎসরিক (প্রতি বছরে)'), ('one_time', 'এককালীন')], default='none', max_length=20, verbose_name='আর্থিক সহায়তার প্রতিশ্রুতি'),
        ),
    ]
