# Generated by Django 5.2.15 on 2026-08-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_volunteer_contribution_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='district',
            field=models.CharField(blank=True, default='নওগাঁ', max_length=100, verbose_name='জেলা'),
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='division',
            field=models.CharField(blank=True, default='রাজশাহী', max_length=100, verbose_name='বিভাগ'),
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='upazila',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='উপজেলা / থানা'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='district',
            field=models.CharField(blank=True, default='নওগাঁ', max_length=100, verbose_name='জেলা'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='division',
            field=models.CharField(blank=True, default='রাজশাহী', max_length=100, verbose_name='বিভাগ'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='upazila',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='উপজেলা / থানা'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='location',
            field=models.CharField(help_text='Area / Address', max_length=255, verbose_name='ঠিকানা / এলাকা'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ঠিকানা / স্থানীয় ঠিকানা'),
        ),
    ]
