# Generated by Django 5.2.15 on 2026-08-23 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_blooddonor_district_blooddonor_division_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ঠিকানা'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='যোগদানের তারিখ'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='custom_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='কাস্টম পদবী (যদি অন্যান্য হয়)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল এড্রেস'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='সদস্য আইডি'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ফোন নম্বর'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to=settings.AUTH_USER_MODEL, verbose_name='ইউজার অ্যাকাউন্ট'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, verbose_name='সংক্ষিপ্ত বিবরণ'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='ছবি'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='পূর্ণ নাম'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0, help_text='Order to display on the team page', verbose_name='প্রদর্শনের ক্রম'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=100, verbose_name='পদবী / ভূমিকা'),
        ),
    ]
