# Generated by Django 5.2.15 on 2026-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_alter_teammember_options_teammember_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='district',
            field=models.CharField(blank=True, default='নওগাঁ', max_length=100, null=True, verbose_name='জেলা'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='division',
            field=models.CharField(blank=True, default='রাজশাহী', max_length=100, null=True, verbose_name='বিভাগ'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='upazila',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='উপজেলা / থানা'),
        ),
    ]
