# Generated by Django 5.2.15 on 2026-09-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_teammember_district_teammember_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True, verbose_name='রক্তের গ্রুপ'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_public_details',
            field=models.BooleanField(default=True, verbose_name='মোবাইল নম্বর ও বিস্তারিত তথ্য সকলের জন্য প্রদর্শন করতে চান?'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_donated',
            field=models.DateField(blank=True, null=True, verbose_name='সর্বশেষ রক্তদানের তারিখ'),
        ),
    ]
