# Generated by Django 5.2.15 on 2026-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_teammember_blood_group_teammember_is_public_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='জেলা'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='division',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='বিভাগ'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Area / Address', max_length=255, verbose_name='ঠিকানা / এলাকা'),
        ),
    ]
