# Generated by Django 4.2.30 on 2026-10-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0011_alter_blooddonor_district_alter_blooddonor_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='payment_method',
            field=models.CharField(blank=True, default='Free / Existing', max_length=50, verbose_name='পেমেন্ট মেথড'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid (পরিশোধিত নয়)'), ('pending', 'Pending (যাচাই বাকি)'), ('paid', 'Paid (পরিশোধিত)')], default='paid', max_length=20, verbose_name='পেমেন্ট স্ট্যাটাস'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='নিবন্ধন ফি (টাকা)'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='sender_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='প্রেরক অ্যাকাউন্ট / মোবাইল নম্বর'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='গেটওয়ে ট্রানজেকশন আইডি'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ট্রানজেকশন আইডি (TrxID)'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
