# Generated by Django 4.2.30 on 2026-10-04 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteers', '0012_volunteer_payment_method_volunteer_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='টোকেন')),
                ('role', models.CharField(max_length=100, verbose_name='পদবি')),
                ('custom_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='কাস্টম পদবি')),
                ('target_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='যার জন্য তৈরি (ঐচ্ছিক)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('is_used', models.BooleanField(default=False, verbose_name='ব্যবহৃত হয়েছে')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='ব্যবহারের সময়')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
                ('registered_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='volunteers.teammember', verbose_name='নিবন্ধিত সদস্য')),
            ],
            options={
                'verbose_name': 'টিম ইনভাইটেশন লিংক',
                'verbose_name_plural': 'টিম ইনভাইটেশন লিংকসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
