# Generated by Django 4.2.30 on 2026-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0013_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='হোমপেজের শীর্ষ নেতৃত্ব সেকশনে প্রদর্শন করবেন কিনা (সর্বোচ্চ ১৫ জন)', verbose_name='হোমপেজে প্রদর্শন'),
        ),
    ]
