"""
Django settings for hello_naogaon project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Reading .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-development-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# To handle CSRF issues with cloud IDEs and other proxies
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://localhost:8000',
    'https://localhost:8000',
    'http://127.0.0.1:8000',
    'https://*.gitpod.io',
    'https://*.github.dev',
    'https://*.app.github.dev',
])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom apps
    'core',
    'programs',
    'news',
    'gallery',
    'volunteers',
    'donations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hello_naogaon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.admin_dashboard_stats',
            ],
        },
    },
]

WSGI_APPLICATION = 'hello_naogaon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}

# Ensure MySQL/MariaDB database connection uses utf8mb4 encoding
if DATABASES['default']['ENGINE'] == 'django.db.backends.mysql':
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].update({
        'charset': 'utf8mb4',
        'init_command': "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'",
    })


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Set default language to English (United States)
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = env('STATIC_URL', default='/static/')
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = env('STATIC_ROOT', default=BASE_DIR / 'staticfiles')

MEDIA_URL = env('MEDIA_URL', default='/media/')
MEDIA_ROOT = env('MEDIA_ROOT', default=BASE_DIR / 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect users to the home page after login/logout
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

JAZZMIN_SETTINGS = {
    "site_title": "Helpline Hello Naogaon Admin",
    "site_header": "Helpline Hello Naogaon",
    "site_brand": "Hello Naogaon Admin",
    "welcome_sign": "হেল্পলাইন হ্যালো নওগাঁ - অ্যাডমিন প্যানেলে স্বাগতম",
    "copyright": "Helpline Hello Naogaon",

    # Top Menu Links
    "topmenu_links": [
        {"name": "ওয়েবসাইট দেখুন", "url": "/", "new_window": True},
        {"name": "আমাদের সম্পর্কে", "url": "/about/", "new_window": True},
        {"name": "যোগাযোগের বার্তা", "model": "core.contactmessage"},
    ],

    "usermenu_links": [
        {"name": "ওয়েবসাইটে ফিরে যান", "url": "/", "new_window": True},
    ],

    # App and model ordering
    "order_with_respect_to": [
        "core.sitesetting",
        "core.statcounter",
        "core.aboutimage",
        "core.contactmessage",
        "programs.program",
        "programs.event",
        "programs.successstory",
        "news.article",
        "news.category",
        "gallery.photo",
        "gallery.album",
        "volunteers.blooddonor",
        "volunteers.volunteer",
        "volunteers.teammember",
        "donations.bank",
        "donations.qrcode",
        "donations.donationmethod",
        "donations.campaign",
        "auth",
    ],

    # Custom Icons for all apps and models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users",

        "core": "fas fa-cogs",
        "core.sitesetting": "fas fa-sliders-h text-success",
        "core.statcounter": "fas fa-sort-numeric-up text-info",
        "core.aboutimage": "fas fa-images text-warning",
        "core.contactmessage": "fas fa-envelope-open-text text-danger",

        "programs": "fas fa-hands-helping",
        "programs.program": "fas fa-hand-holding-heart text-success",
        "programs.event": "fas fa-calendar-alt text-primary",
        "programs.successstory": "fas fa-star text-warning",

        "news": "fas fa-newspaper",
        "news.article": "fas fa-file-alt text-info",
        "news.category": "fas fa-folder text-secondary",

        "gallery": "fas fa-photo-video",
        "gallery.photo": "fas fa-image text-success",
        "gallery.album": "fas fa-folder-plus text-primary",

        "volunteers": "fas fa-user-friends",
        "volunteers.blooddonor": "fas fa-tint text-danger",
        "volunteers.volunteer": "fas fa-user-check text-success",
        "volunteers.teammember": "fas fa-id-card text-info",

        "donations": "fas fa-hand-holding-usd",
        "donations.bank": "fas fa-university text-success",
        "donations.qrcode": "fas fa-qrcode text-dark",
        "donations.donationmethod": "fas fa-wallet text-info",
        "donations.campaign": "fas fa-bullhorn text-warning",
        "donations.donationpagecontent": "fas fa-file-invoice",
        "donations.donationimpact": "fas fa-chart-line",
        "donations.emergencyappeal": "fas fa-exclamation-triangle text-danger",
        "donations.faq": "fas fa-question-circle text-primary",
        "donations.donationstatistic": "fas fa-chart-bar",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # UI Customizations
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "related_modal_active": True,
    "custom_css": "css/admin_custom.css",
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-success",
    "navbar": "navbar-success navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


# Security settings for production deployment (cPanel / HTTPS proxy)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
X_FRAME_OPTIONS = 'SAMEORIGIN'


