# Generated by Django 5.2.15 on 2026-06-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(help_text='e.g., bKash, Bank Transfer', max_length=100)),
                ('account_details', models.TextField(help_text='Account number or routing info')),
                ('instructions', models.TextField(blank=True, help_text='Any specific instructions for the donor')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
