# Generated by Django 5.2.15 on 2026-07-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donationmethod",
            old_name="method_name",
            new_name="name",
        ),
    ]
