# Generated by Django 5.2.15 on 2026-07-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_rename_method_name_donationmethod_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=200)),
                ("account_number", models.CharField(max_length=50)),
                ("branch", models.CharField(blank=True, max_length=100)),
                ("swift_code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="donations/campaigns/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DonationImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=255)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, help_text="e.g., 'fas fa-home'", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Donation Impact",
                "verbose_name_plural": "Donation Impacts",
                "ordering": ["amount"],
            },
        ),
        migrations.CreateModel(
            name="DonationPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="আপনার দানে, হাসি ফুটবে ও মুখে", max_length=200
                    ),
                ),
                ("hero_subtitle", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="donations/hero/"
                    ),
                ),
                ("intro_title", models.CharField(default="দান করুন", max_length=200)),
                ("intro_text", models.TextField(blank=True)),
                (
                    "why_donate_title",
                    models.CharField(default="কেন দান করবেন?", max_length=200),
                ),
                ("why_donate_text", models.TextField(blank=True)),
                (
                    "transparency_title",
                    models.CharField(default="স্বচ্ছতা", max_length=200),
                ),
                ("transparency_text", models.TextField(blank=True)),
                (
                    "contact_title",
                    models.CharField(default="দানের জন্য যোগাযোগ", max_length=200),
                ),
                ("contact_text", models.TextField(blank=True)),
                (
                    "thank_you_title",
                    models.CharField(default="ধন্যবাদ", max_length=200),
                ),
                ("thank_you_text", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Donation Page Content",
                "verbose_name_plural": "Donation Page Contents",
            },
        ),
        migrations.CreateModel(
            name="DonationStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, help_text="e.g., 'fas fa-users'", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Donation Statistic",
                "verbose_name_plural": "Donation Statistics",
            },
        ),
        migrations.CreateModel(
            name="EmergencyAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="donations/appeals/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Emergency Appeal",
                "verbose_name_plural": "Emergency Appeals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AlterModelOptions(
            name="donationmethod",
            options={
                "verbose_name": "Donation Method",
                "verbose_name_plural": "Donation Methods",
            },
        ),
        migrations.RemoveField(
            model_name="donationmethod",
            name="account_details",
        ),
        migrations.RemoveField(
            model_name="donationmethod",
            name="instructions",
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="donations/qrcodes/")),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Merchant number, account name",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qrcodes",
                        to="donations.donationmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code",
                "verbose_name_plural": "QR Codes",
            },
        ),
    ]
