# Generated by Django 4.2.30 on 2026-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_bank_campaign_donationimpact_donationpagecontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpagecontent',
            name='hero_title',
            field=models.CharField(default='চলুন আনন্দ ছড়াই', max_length=200),
        ),
    ]
