# Generated by Django 4.2.30 on 2026-08-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donationpagecontent_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'আয় / অনুদান (Income)'), ('expense', 'ব্যয় / খরচ (Expense)')], default='income', max_length=10)),
                ('title', models.CharField(help_text='খাতের নাম বা শিরোনাম', max_length=255)),
                ('category', models.CharField(default='সাধারণ অনুদান', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='bKash', max_length=50)),
                ('trx_id', models.CharField(blank=True, help_text='Transaction ID / Receipt No', max_length=100)),
                ('donor_name', models.CharField(blank=True, help_text='দাতা বা গ্রহণকারীর নাম', max_length=200)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='donations/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Financial Transaction',
                'verbose_name_plural': 'Financial Transactions',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
