# Generated by Django 5.2.15 on 2026-08-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_financialtransaction'),
        ('programs', '0002_alter_program_options_program_badge_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200, verbose_name='দাতা/সহায়তাকারীর নাম')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('donor_phone', models.CharField(max_length=20, verbose_name='মোবাইল নম্বর')),
                ('membership_id', models.CharField(blank=True, help_text='মেম্বারশিপ আইডি (যদি থাকে)', max_length=50, null=True, verbose_name='মেম্বারশিপ আইডি')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='আর্থিক সহায়তার পরিমাণ (BDT)')),
                ('payment_method', models.CharField(default='bKash', max_length=50, verbose_name='পেমেন্ট মেথড')),
                ('trx_id', models.CharField(blank=True, max_length=100, verbose_name='ট্রানজেকশন আইডি / Trx ID')),
                ('note', models.TextField(blank=True, verbose_name='মন্তব্য / নোট')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ (Pending)'), ('approved', 'অনুমোদিত (Approved)'), ('rejected', 'বাতিল (Rejected)')], default='approved', max_length=20, verbose_name='স্ট্যাটাস')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তারিখ ও সময়')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='programs.program', verbose_name='কার্যক্রম (Program)')),
            ],
            options={
                'verbose_name': 'Program Donation',
                'verbose_name_plural': 'Program Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
