# Generated by Django 5.2.15 on 2026-08-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_programdonation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programdonation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Financial Contribution / Donation', 'verbose_name_plural': 'Financial Contributions / Donations'},
        ),
        migrations.AddField(
            model_name='bank',
            name='routing_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donationmethod',
            name='account_number',
            field=models.CharField(blank=True, help_text='e.g., 017XXXXXXXX', max_length=100),
        ),
        migrations.AddField(
            model_name='donationmethod',
            name='account_type',
            field=models.CharField(blank=True, default='Personal', help_text='e.g., Personal, Merchant, Agent', max_length=50),
        ),
        migrations.AddField(
            model_name='donationmethod',
            name='icon_class',
            field=models.CharField(blank=True, default='fas fa-mobile-alt', help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='donationmethod',
            name='instructions',
            field=models.TextField(blank=True, help_text='পেমেন্ট করার নিয়মাবলী বা নির্দেশনা'),
        ),
        migrations.AddField(
            model_name='programdonation',
            name='donation_type',
            field=models.CharField(choices=[('volunteer', 'স্বেচ্ছাসেবক অনুদান / মাসিক চাঁদা'), ('general', 'সাধারণ আর্থিক সহায়তা'), ('program', 'কার্যক্রম ভিত্তিক সহায়তা'), ('emergency', 'জরুরি ত্রাণ ও চিকিৎসা তহবিল')], default='general', max_length=30, verbose_name='সহায়তার ধরন'),
        ),
        migrations.AddField(
            model_name='programdonation',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'এককালীন'), ('monthly', 'মাসিক'), ('weekly', 'সাপ্তাহিক'), ('yearly', 'বাৎসরিক')], default='one_time', max_length=20, verbose_name='পর্যায়কাল / ফ্রিকোয়েন্সি'),
        ),
        migrations.AlterField(
            model_name='donationmethod',
            name='name',
            field=models.CharField(help_text='e.g., bKash, Nagad, Rocket, Bank Transfer', max_length=100),
        ),
    ]
