# Generated by Django 5.2.15 on 2026-08-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_programdonation_options_bank_routing_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdonation',
            name='bank_tran_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ব্যাংক / ভ্যালিডেশন ট্রানজেকশন আইডি'),
        ),
        migrations.AddField(
            model_name='programdonation',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='পেমেন্ট চ্যানেল / কার্ড টাইপ'),
        ),
        migrations.AddField(
            model_name='programdonation',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='গেটওয়ে ট্রানজেকশন আইডি'),
        ),
        migrations.AlterField(
            model_name='programdonation',
            name='payment_method',
            field=models.CharField(default='Online Gateway', max_length=50, verbose_name='পেমেন্ট মেথড'),
        ),
        migrations.AlterField(
            model_name='programdonation',
            name='status',
            field=models.CharField(choices=[('pending', 'অপেক্ষমাণ (Pending)'), ('approved', 'সফল / অনুমোদিত (Approved)'), ('failed', 'ব্যর্থ (Failed)'), ('cancelled', 'বাতিল (Cancelled)')], default='pending', max_length=20, verbose_name='স্ট্যাটাস'),
        ),
    ]
