# Generated by Django 5.2.15 on 2026-08-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_programdonation_bank_tran_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('sslcommerz', 'SSLCommerz (বিকাশ, নগদ, রকেট, উপায় ও সকল ব্যাংক কার্ড)'), ('shurjopay', 'ShurjoPay Payment Gateway'), ('aamarpay', 'AamarPay Payment Gateway'), ('bkash', 'bKash Direct Merchant PGW')], default='sslcommerz', max_length=50, verbose_name='পেমেন্ট গেটওয়ে প্রোভাইডার')),
                ('store_id', models.CharField(blank=True, help_text='SSLCommerz Store ID / Merchant ID', max_length=150, verbose_name='স্টোর আইডি / মার্চেন্ট আইডি')),
                ('store_password', models.CharField(blank=True, help_text='SSLCommerz Store Password / API Secret', max_length=150, verbose_name='স্টোর পাসওয়ার্ড / সিক্রেট কি')),
                ('is_sandbox', models.BooleanField(default=True, help_text='স্যান্ডবক্স / টেস্ট মোড চালু রাখতে টিক দিন। লাইভ ট্রানজেকশনের জন্য টিক তুলে দিন।', verbose_name='স্যান্ডবক্স (টেস্ট মোড)')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'পেমেন্ট গেটওয়ে কনফিগারেশন',
                'verbose_name_plural': 'পেমেন্ট গেটওয়ে কনফিগারেশন',
            },
        ),
    ]
