# Generated by Django 5.2.15 on 2026-08-23 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_paymentgatewaysetting'),
        ('programs', '0003_program_raised_amount_program_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='programs.program', verbose_name='কার্যক্রম (Program)'),
        ),
    ]
