# Generated by Django 4.2.30 on 2026-10-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_financialtransaction_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdonation',
            name='sender_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='প্রেরকের নম্বর / অ্যাকাউন্ট নম্বর'),
        ),
        migrations.AlterField(
            model_name='programdonation',
            name='status',
            field=models.CharField(choices=[('pending', 'অপেক্ষমাণ (Pending)'), ('approved', 'সফল / অনুমোদিত (Approved)'), ('rejected', 'বাতিল / প্রত্যাখ্যাত (Rejected)'), ('failed', 'ব্যর্থ (Failed)'), ('cancelled', 'বাতিল (Cancelled)')], default='pending', max_length=20, verbose_name='স্ট্যাটাস'),
        ),
    ]
