# Generated by Django 4.2.30 on 2026-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_programdonation_sender_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdonation',
            name='status',
            field=models.CharField(choices=[('initiated', 'প্রক্রিয়াধীন / শুরু হয়েছে (Initiated)'), ('pending', 'অপেক্ষমাণ (Pending)'), ('approved', 'সফল / অনুমোদিত (Approved)'), ('rejected', 'বাতিল / প্রত্যাখ্যাত (Rejected)'), ('failed', 'ব্যর্থ (Failed)'), ('cancelled', 'বাতিল (Cancelled)')], default='pending', max_length=20, verbose_name='স্ট্যাটাস'),
        ),
    ]
