# Generated by Django 4.2.30 on 2026-10-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_alter_programdonation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdonation',
            name='donation_type',
            field=models.CharField(choices=[('volunteer_registration', 'সদস্য নিবন্ধন ফি'), ('volunteer', 'স্বেচ্ছাসেবক অনুদান / মাসিক চাঁদা'), ('general', 'সাধারণ আর্থিক সহায়তা'), ('program', 'কার্যক্রম ভিত্তিক সহায়তা'), ('emergency', 'জরুরি ত্রাণ ও চিকিৎসা তহবিল')], default='general', max_length=30, verbose_name='সহায়তার ধরন'),
        ),
    ]
