# Generated by Django 4.2.30 on 2026-10-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_alter_programdonation_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewaysetting',
            name='is_sandbox',
            field=models.BooleanField(default=False, help_text='স্যান্ডবক্স / টেস্ট মোড চালু রাখতে টিক দিন। লাইভ ট্রানজেকশনের জন্য টিক তুলে দিন।', verbose_name='স্যান্ডবক্স (টেস্ট মোড)'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaysetting',
            name='provider',
            field=models.CharField(choices=[('paystation', 'PayStation Payment Gateway (বিকাশ, নগদ, রকেট, উপায় ও সকল ব্যাংক কার্ড)'), ('sslcommerz', 'SSLCommerz (বিকাশ, নগদ, রকেট, উপায় ও সকল ব্যাংক কার্ড)'), ('shurjopay', 'ShurjoPay Payment Gateway'), ('aamarpay', 'AamarPay Payment Gateway'), ('bkash', 'bKash Direct Merchant PGW')], default='paystation', max_length=50, verbose_name='পেমেন্ট গেটওয়ে প্রোভাইডার'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaysetting',
            name='store_id',
            field=models.CharField(blank=True, help_text='PayStation / Gateway Store ID (e.g. 6973-XXXXXX)', max_length=150, verbose_name='স্টোর আইডি / মার্চেন্ট আইডি'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaysetting',
            name='store_password',
            field=models.CharField(blank=True, help_text='PayStation / Gateway Password / Secret Key', max_length=150, verbose_name='স্টোর পাসওয়ার্ড / সিক্রেট কি'),
        ),
    ]
