# Generated by Django 4.2.30 on 2026-10-07 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_alter_paymentgatewaysetting_is_sandbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='donations.programdonation', verbose_name='প্রাপ্ত অনুদান লিংক'),
        ),
    ]
