# Generated by Django 4.2.30 on 2026-10-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_financialtransaction_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='is_manual_entry',
            field=models.BooleanField(default=False, help_text='এডমিন নিজে ড্যাশবোর্ড থেকে সরাসরি ইনপুট দিয়েছেন কিনা', verbose_name='এডমিনের নিজস্ব এন্ট্রি'),
        ),
    ]
