# Generated by Django 4.2.30 on 2026-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AddField(
            model_name='program',
            name='badge_color',
            field=models.CharField(default='success', help_text='Color: danger, success, warning, primary, info', max_length=30),
        ),
        migrations.AddField(
            model_name='program',
            name='icon_class',
            field=models.CharField(default='fas fa-hands-helping', help_text="e.g. 'fas fa-tint', 'fas fa-book-reader'", max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for card display', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
    ]
