# Generated by Django 5.2.15 on 2026-08-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_options_program_badge_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='সংগৃহীত অনুদানের পরিমাণ', max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='প্রোগ্রামের জন্য প্রয়োজনীয় আর্থিক সহায়তার পরিমাণ (ঐচ্ছিক)', max_digits=12, null=True),
        ),
    ]
