# Generated by Django 4.2.30 on 2026-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_raised_amount_program_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_featured_board',
            field=models.BooleanField(default=False, help_text='চলমান কার্যক্রম হিসেবে হোমপেজে ৫ সেকেন্ডের পপআপ বোর্ড/ব্যানার আকারে প্রদর্শন করবে', verbose_name='সামনে বোর্ড/ব্যানার পপআপ'),
        ),
    ]
